# Generated by Django 4.2.7 on 2023-11-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
